/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.SecurityGenarator;
import Code.SendMail;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Zunaid
 */
public class Go extends javax.swing.JFrame {

    /**
     * Creates new form Go
     */
    public Go() {
        initComponents();
        this.getContentPane().setBackground(Color.white);

    }

    SecurityGenarator secure = new SecurityGenarator("e10adc3949ba59abbe56e057f20f883e");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goBtn = new javax.swing.JButton();
        jPassFiled = new javax.swing.JTextField();
        emailBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goBtn.setFont(new java.awt.Font("KG Broken Vessels Sketch", 1, 18)); // NOI18N
        goBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/go1.png"))); // NOI18N
        goBtn.setText("GO");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        jPassFiled.setText("Pass / Temp Code");
        jPassFiled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPassFiledMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPassFiledMouseExited(evt);
            }
        });

        emailBtn.setFont(new java.awt.Font("KG Broken Vessels Sketch", 1, 18)); // NOI18N
        emailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/email.png"))); // NOI18N
        emailBtn.setText(" Email a Temp Code");
        emailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPassFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(emailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPassFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(emailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
        if (secure.genarateMd5(jPassFiled.getText()).equals(secure.getCurrentPass())
                || secure.genarateMd5(jPassFiled.getText()).equals(secure.getRandom())) {
            PhotoUpload pu = new PhotoUpload();
            pu.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_goBtnActionPerformed

    private void jPassFiledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassFiledMouseClicked
        // TODO add your handling code here:
       if (jPassFiled.getText().equals("Pass / Temp Code")) {
           jPassFiled.setText("");
       }
    }//GEN-LAST:event_jPassFiledMouseClicked

    private void jPassFiledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassFiledMouseExited
        // TODO add your handling code here:
        if (jPassFiled.getText().isEmpty()) {
            jPassFiled.setText("Pass / Temp Code");
        }
    }//GEN-LAST:event_jPassFiledMouseExited

    private void emailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBtnActionPerformed
        try {
            // TODO add your handling code here:
            SendMail mail = new SendMail();
            mail.emailMe(secure.genarateRandom().toString());
            emailBtn.setEnabled(false);
            JOptionPane.showMessageDialog(rootPane, "Email sent, Please check inbox !!");

        } catch (MessagingException ex) {
            Logger.getLogger(Go.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Email not sent, Please try again !!");        
        }
    }//GEN-LAST:event_emailBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Go.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Go.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Go.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Go.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Go().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emailBtn;
    private javax.swing.JButton goBtn;
    private javax.swing.JTextField jPassFiled;
    // End of variables declaration//GEN-END:variables
}
